import Head from "next/head";
import { Inter } from "@next/font/google";
import { FormEvent, InputHTMLAttributes, useRef, useState } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const inputRef = useRef<InputHTMLAttributes<HTMLInputElement>>(null);
  const [answer, setAnswer] = useState<string | null>(null);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    const res = await axios.post(
      "/api/ask",
      {
        question: inputRef?.current?.value,
      },
      {
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    setAnswer(res.data.answer);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center min-h-screen text-center">
        <div>
          <form className="space-x-3" onSubmit={handleSubmit}>
            <input
              placeholder="Ask a question.."
              type="text"
              className="form-input w-96"
              ref={inputRef}
            />

            <button className="p-2">Ask</button>
          </form>

          {answer && <p className="mt-5 max-w-2xl mx-auto">{answer}</p>}
        </div>
      </main>
    </>
  );
}
